import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/mainpageservicespopup">MainPageServicesPopUP</Link>
        </li>
        <li>
          <Link to="/frameeleven">FrameEleven</Link>
        </li>
        <li>
          <Link to="/mainpageaitypepopup">MainPageAITypePopUp</Link>
        </li>
        <li>
          <Link to="/webappfive">WebappFive</Link>
        </li>
        <li>
          <Link to="/uploadtotostandingsoption">UploadtoTOStandingsOption</Link>
        </li>
        <li>
          <Link to="/webappsix">WebappSix</Link>
        </li>
        <li>
          <Link to="/o">O</Link>
        </li>
        <li>
          <Link to="/mainpagepaymentmethodpopup">
            MainPagePaymentMethodPopUP
          </Link>
        </li>
        <li>
          <Link to="/signupinformationsrequiredbussinessone">
            SignupinformationsrequiredBussinessone
          </Link>
        </li>
        <li>
          <Link to="/webapp4topage">Webapp4TOPage</Link>
        </li>
        <li>
          <Link to="/signupinformationsrequiredprofessionalone">
            SignupinformationsrequiredProfessionalone
          </Link>
        </li>
        <li>
          <Link to="/loginpage">Loginpage</Link>
        </li>
        <li>
          <Link to="/recoverpassword">Recoverpassword</Link>
        </li>
        <li>
          <Link to="/frametwentyone">FrameTwentyOne</Link>
        </li>
        <li>
          <Link to="/homepage">HomePage</Link>
        </li>
        <li>
          <Link to="/navbartablet">NavbarTablet</Link>
        </li>
        <li>
          <Link to="/gettingthecodeimg">GettingthecodeIMG</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
